apt-get install mingw32
apt-get install cmake
apt-get install cmake-qt-gui
apt-get install g++
apt-get install libpthread-stubs0-dev
apt-get install libgl1-mesa-dev
apt-get install libx11-dev
apt-get install libxrandr-dev
apt-get install libfreetype6-dev
apt-get install libglew1.5-dev
apt-get install libjpeg8-dev
apt-get install libgpgme11-dev
apt-get install libsndfile1-dev
apt-get install libopenal-dev
apt-get install libudev-dev
apt-get install libgles1-mesa-dev
apt-get install libgles2-mesa-dev
apt-get install libgle-dev
apt-get install libglu1-mesa-dev
apt-get install libgl1-mesa-dev
apt-get install freeglut3-dev
apt-get install libsfml-dev
apt-get install libglewmx-dev